
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[390] =
    {   0,
        0,    0,   78,   76,   77,   75,   21,   76,   76,   70,
       76,    7,    8,    5,    3,    2,    4,   76,    6,   72,
        1,   16,   13,   18,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   20,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,    9,   76,   10,   75,   15,
        0,   69,   70,   70,   70,   11,    0,   72,   73,    0,
        0,   72,   17,   14,   19,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   24,   70,   70,
       70,   70,   70,   70,   70,   12,    0,   74,   69,    0,

        0,    0,   73,   72,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   26,   70,   27,   22,   70,
       70,   70,   70,    0,    0,    0,   73,    0,    0,   72,
       70,   70,   70,   70,   56,   70,   70,   70,   54,   70,
       70,   70,   70,   70,   70,   70,   63,   70,   23,   70,
       70,   70,   70,   70,   68,   70,    0,    0,    0,   73,
       72,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,

       70,   25,    0,    0,    0,    0,    0,   73,    0,    0,
       72,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   28,    0,   71,   71,   71,   71,   71,   29,
       55,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,
        0,   70,   70,   58,   70,   60,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   70,   70,   70,

       51,   70,   70,   70,   70,   70,   70,   70,   70,   31,
       70,   70,   70,   59,   70,   70,   70,   70,   53,   70,
       70,   70,   70,   70,   70,   70,   40,   48,   49,   50,
       70,   70,   67,   42,   38,   70,   70,   70,   30,   70,
       70,   37,   70,   70,   70,   70,   70,   70,   45,   46,
       47,   70,   61,   70,   41,   36,   70,   70,   70,   52,
       57,   70,   70,   64,   70,   66,   70,   70,   62,   39,
       70,   70,   70,   32,   70,   65,   70,   70,   34,   70,
       43,   70,   35,   70,   70,   70,   33,   44,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    1,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    1,   19,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       27,   27,   29,   27,   27,   30,   31,   27,   32,   33,
       27,   34,   35,   36,   27,   37,   38,   39,   40,   41,
       27,   27,   27,   42,   43,   27,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   27,   53,   54,   55,   56,
       57,   58,   27,   59,   60,   61,   62,   63,   64,   27,
       65,   66,   67,   68,   69,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[399] =
    {   0,
        0,    0,  439, 1205, 1205,   66,  411,    0,    0,   53,
      417, 1205, 1205, 1205,   56, 1205,   57,  407,   73,   62,
     1205,  378,  375,  374,   61,   63,   64,   70,   71,   73,
       83,   82,   79,   80,   81,   89,   90,  114,  124,  102,
      132,  115,  130,  147,  134, 1205,  318, 1205,  157, 1205,
      173,  152,  144,  160,  166, 1205,  349,  174,  329,  325,
      319,  178, 1205, 1205, 1205,  164,  177,  179,  181,  187,
      189,  191,  198,  199,  201,  205,  208,  207,  218,  211,
      209,  215,  222,  226,  232,  240,  242,  255,  256,  258,
      273,  265,  269,  277,  279, 1205,  299,  305,  244,  321,

      282,  294,  276,  238,  292,  295,  296,  298,  302,  309,
      312,  315,  322,  332,  333,  336,  335,  342,  343,  345,
      346,  355,  356,  357,  359,  365,  366,  367,  369,  375,
      379,  387,  388,  249,  267,  257,  249,  248,  239,  268,
      390,  396,  397,  398,  400,  406,  404,  433,  410,  423,
      441,  425,  427,  442,  448,  457,  459,  467,  468,  469,
      475,  476,  479,  477,  478,  486,  232,  197,  193,  183,
      288,  485,  487,  488,  489,  495,  498,  501,  502,  504,
      517,  524,  505,  527,  528,  534,  538,  541,  542,  551,
      552,  558,  554,  555,  562,  564,  570,  574,  580,  583,

      586,  587,  132,  168,  154,  151,  148,  142,  127,  121,
      306,  590,  594,  597,  604,  610,  607,  619,  617,  620,
      623,  626,  627,  634,  640,  636,  652,  642,  653,  655,
      656,  663,  673,  676,  677,  684,  683,  686,  687,  694,
      695,  697,  698,   76,   98,   92,   91,   77,  328,  704,
      706,  708,  717,  719,  723,  725,  726,  727,  734,  737,
      735,  741,  743,  745,  744,  747,  753,  755,  757,  767,
      774,  782,  783,  784,  790,  792,  794,  800,  804,  806,
       84,  808,  810,  816,  824,  826,  827,  828,  835,  834,
      838,  842,  841,  848,  849,  852,  855,  856,  862,  864,

      874,  873,  875,  883,  884,  893,  886,  901,  899,  902,
      908,  909,  911,  910,  917,  918,  921,  928,  929,  937,
      935,  938,  939,  941,  945,  953,  959,  963,  970,  974,
      976,  980,  978,  984,  987,  990,  991,  993,  994,  997,
     1000, 1001, 1003, 1004, 1007, 1010, 1011, 1013, 1020, 1021,
     1030, 1032, 1034, 1038, 1040, 1046, 1048, 1050, 1056, 1057,
     1059, 1060, 1063, 1066, 1069, 1067, 1070, 1077, 1079, 1083,
     1085, 1087, 1089, 1091, 1095, 1098, 1101, 1102, 1104, 1105,
     1111, 1112, 1114, 1118, 1122, 1124, 1125, 1133, 1205, 1180,
     1183,   82, 1186, 1189, 1192, 1195, 1198, 1201

    } ;

static const flex_int16_t yy_def[399] =
    {   0,
      389,    1,  389,  389,  389,  389,  389,  390,  391,  392,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  393,
      389,  389,  389,  389,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  389,  389,  389,  389,  389,
      390,  391,  392,  389,  392,  389,  389,  389,  389,  389,
      389,  393,  389,  389,  389,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  389,  390,  390,  391,  389,

      389,  394,  394,  395,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  389,  389,  394,  394,  389,  389,  395,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  389,  396,  397,  397,
      398,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  389,  389,  396,  389,  397,  397,  389,  389,
      398,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  389,  389,  396,  397,  397,  398,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      389,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,

      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,  392,  392,
      392,  392,  392,  392,  392,  392,  392,  392,    0,  389,
      389,  389,  389,  389,  389,  389,  389,  389

    } ;

static const flex_int16_t yy_nxt[1275] =
    {   0,
        4,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   10,   10,   25,   26,   10,   27,   10,   28,
       29,   10,   30,   31,   32,   33,   10,   34,   10,   10,
       10,   35,   10,   10,   36,   10,   10,   37,   38,   10,
       10,   39,   10,   40,   10,   41,   10,   10,   42,   43,
       44,   10,   10,   45,   10,   10,   46,   47,   48,   49,
       54,   57,   57,   58,   58,   55,   49,   61,   54,   62,
       54,   54,   49,   55,   53,   55,   55,   54,   54,   49,
       54,   54,   55,   55,  248,   55,   54,   54,   54,   54,

       54,   55,   55,   55,   55,   55,   54,   54,  247,  246,
       67,   55,   55,   70,   68,  245,   72,   66,  281,   54,
       69,   49,   79,   81,   55,   76,   49,   71,   49,   77,
       73,   54,   54,   49,   74,   49,   55,   55,  248,   75,
       80,   54,   78,   83,  247,   82,   55,   54,   49,   54,
       49,   54,   55,   99,   55,   99,   55,   84,   90,  248,
       49,   54,   92,   49,   54,  247,   55,   85,  246,   55,
       86,  246,   88,   49,   97,   87,   97,   54,   98,   89,
      101,   54,  100,   54,   95,  245,   55,   91,   55,   57,
       93,   58,   91,   61,   54,  104,   54,  244,   54,   55,

      208,   55,   91,   55,   54,   94,   54,   91,   54,   55,
      207,   55,   49,   55,  205,   54,   54,   49,   54,  105,
       55,   55,   54,   55,   54,   54,   54,   55,   54,   55,
       55,   55,   54,   55,  108,   54,  106,   55,  107,   54,
       55,  112,  109,   54,   55,   99,  203,   99,   55,   54,
      117,  110,  111,  139,   55,  140,  170,   54,  113,   54,
      121,  114,   55,  118,   55,  169,  170,  115,  116,  120,
      119,  122,   54,   54,  169,   54,   49,   55,   55,  124,
       55,  123,   54,  139,  168,  171,   54,   55,  125,   49,
       54,   55,  167,  137,   54,   55,   54,  127,  126,   55,

       97,   55,   97,  210,   98,  211,   97,  129,   97,   54,
       98,  136,   54,   54,   55,   54,  128,   55,   55,   54,
       55,  210,  134,  249,   55,  130,   54,  131,   91,   54,
      133,   55,   54,   91,   55,  101,  103,   55,  132,   54,
      142,  143,  102,  210,   55,  249,   59,  141,  145,   54,
       54,  144,   54,   54,   55,   55,  146,   55,   55,   54,
       54,  148,   54,   54,   55,   55,   59,   55,   55,  149,
      152,  147,   54,   54,   54,  150,   54,   55,   55,   55,
      151,   55,   54,   54,   54,   96,   54,   55,   55,   55,
      155,   55,   54,  153,   65,   64,   54,   55,   63,  154,

      156,   55,  161,  159,   54,   54,  157,   54,  158,   55,
       55,  162,   55,   54,   54,   54,  160,   54,   55,   55,
       55,   54,   55,   54,   59,   56,   55,   54,   55,  176,
      164,   50,   55,  177,  165,  178,  163,  172,  389,  179,
       54,  166,   54,  173,   54,   55,  389,   55,  389,   55,
       54,  180,  389,  174,  175,  181,  182,  183,   54,   54,
      184,  185,  186,   55,   55,   54,  389,  187,  188,  389,
       55,  190,  193,  389,   54,  389,   54,  194,  195,   55,
      196,   55,  191,  189,   54,   54,   54,  192,  197,   55,
       55,   55,   54,   54,   54,   54,   54,   55,   55,   55,

       55,   55,   54,   54,   54,   54,   54,   55,   55,   55,
       55,   55,   54,  389,  198,   54,  165,   55,   54,   54,
       55,   54,   54,   55,   55,  389,   55,   55,  389,  389,
      212,  101,  201,  202,   54,  128,  199,  200,  216,   55,
      220,   54,  213,  214,   54,   54,   55,  389,  218,   55,
       55,   54,  215,  219,  217,   54,   55,  389,   54,   54,
       55,  389,  221,   55,   55,  389,  224,  223,   54,   54,
      222,   54,   54,   55,   55,   54,   55,   55,  389,   54,
       55,   54,  389,  226,   55,  225,   55,   54,  229,  230,
      227,   54,   55,  233,  234,  228,   55,   54,  231,  232,

       54,  389,   55,   54,   54,   55,  236,   54,   55,   55,
      235,   54,   55,  237,   54,  238,   55,  241,  239,   55,
      389,   54,  389,  389,   54,  240,   55,   54,  253,   55,
      389,  242,   55,  389,   54,  128,   54,   54,  243,   55,
       54,   55,   55,   54,   54,   55,  389,  389,   55,   55,
      250,   54,  252,   54,  251,  254,   55,   54,   55,   54,
      389,  389,   55,  389,   55,  255,  257,  256,  259,   54,
       54,  258,   54,   54,   55,   55,  389,   55,   55,  389,
       54,  264,  389,  389,  268,   55,  260,  261,  269,  266,
       54,  389,  262,   54,   54,   55,  263,  265,   55,   55,

       54,   54,  270,   54,   54,   55,   55,  267,   55,   55,
      271,   54,   54,  389,   54,   54,   55,   55,  279,   55,
       55,   54,  389,   54,  272,   54,   55,  273,   55,  276,
       55,  277,  389,  389,   54,  278,   54,  274,  275,   55,
       54,   55,   54,   54,   54,   55,  389,   55,   55,   55,
      128,   54,   54,  280,   54,  282,   55,   55,   54,   55,
       54,   54,   54,   55,   54,   55,   55,   55,  389,   55,
       54,  284,   54,  288,   54,   55,  287,   55,  283,   55,
      389,  289,  389,  389,   54,  286,  285,  295,  290,   55,
      389,   54,  389,  389,  296,  291,   55,  293,  294,   54,

       54,   54,  298,  292,   55,   55,   55,   54,  299,   54,
      297,   54,   55,  389,   55,  389,   55,   54,  300,  389,
      301,   54,   55,   54,  308,   54,   55,   54,   55,  303,
       55,  389,   55,   54,  389,  389,  302,  305,   55,  306,
      304,   54,  389,   54,   54,   54,   55,  309,   55,   55,
       55,   54,   54,  311,  307,   54,   55,   55,   54,   54,
       55,  310,  389,   55,   55,   54,   54,  313,  312,   54,
       55,   55,   54,   54,   55,  315,  320,   55,   55,   54,
      389,   54,  389,  389,   55,  318,   55,  314,  316,  319,
       54,   54,   54,  389,  317,   55,   55,   55,  323,  321,

       54,   54,  324,   54,  325,   55,   55,  327,   55,  322,
       54,  326,  328,  329,  330,   55,   54,  389,   54,   54,
      331,   55,  332,   55,   55,   54,   54,   54,   54,  389,
       55,   55,   55,   55,   54,   54,  389,  389,   54,   55,
       55,  333,  334,   55,  337,   54,   54,  336,  389,  335,
       55,   55,   54,  338,   54,   54,   54,   55,   54,   55,
       55,   55,   54,   55,  389,  343,  389,   55,  339,  341,
       54,  340,  389,  342,  389,   55,   54,  349,  350,  351,
       54,   55,  344,  389,  389,   55,  345,   54,  346,  348,
      347,   54,   55,   54,  389,   54,   55,   54,   55,  352,

       55,   54,   55,  354,   54,  353,   55,   54,   54,   55,
       54,   54,   55,   55,   54,   55,   55,   54,   54,   55,
       54,   54,   55,   55,   54,   55,   55,   54,   54,   55,
       54,  389,   55,   55,  355,   55,  356,   54,   54,  389,
      359,  389,   55,   55,  360,  358,  361,   54,  357,   54,
      363,   54,   55,  389,   55,   54,   55,   54,  366,  389,
       55,  362,   55,   54,  365,   54,  389,   54,   55,  367,
       55,  364,   55,   54,   54,  368,   54,   54,   55,   55,
       54,   55,   55,   54,   54,   55,   54,   54,   55,   55,
      389,   55,   55,  389,   54,  370,   54,  371,  369,   55,

       54,   55,   54,  373,   54,   55,   54,   55,   54,   55,
      374,   55,   54,   55,  372,   54,  375,   55,   54,   54,
       55,   54,   54,   55,   55,  376,   55,   55,   54,   54,
      379,   54,  389,   55,   55,   54,   55,  377,  389,   54,
       55,   54,   54,  378,   55,  383,   55,   55,  389,  380,
       54,  389,  389,  381,  389,   55,  384,  389,  389,  389,
      389,  389,  382,  389,  389,  389,  389,  389,  389,  387,
      385,  389,  389,  389,  386,  389,  389,  389,  389,  388,
       51,  389,   51,   52,  389,   52,   60,  389,   60,  135,
      389,  135,  138,  389,  138,  204,  389,  204,  206,  389,

      206,  209,  389,  209,    3,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389
    } ;

static const flex_int16_t yy_chk[1275] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    6,
       10,   15,   17,   15,   17,   10,   19,   20,   25,   20,
       26,   27,    6,   25,  392,   26,   27,   28,   29,   19,
       30,  281,   28,   29,  248,   30,   33,   34,   35,   32,

       31,   33,   34,   35,   32,   31,   36,   37,  247,  246,
       26,   36,   37,   28,   26,  245,   30,   25,  244,   40,
       27,    6,   33,   34,   40,   32,    6,   29,   19,   32,
       31,   38,   42,   19,   31,   41,   38,   42,  210,   31,
       33,   39,   32,   37,  209,   36,   39,   43,   41,   41,
       44,   45,   43,   52,   41,   52,   45,   38,   40,  208,
       49,   53,   42,   44,   44,  207,   53,   38,  206,   44,
       38,  205,   39,   49,   51,   38,   51,   54,   51,   39,
       55,   66,   54,   55,   45,  204,   66,   41,   55,   58,
       43,   58,   41,   62,   67,   62,   68,  203,   69,   67,

      170,   68,   44,   69,   70,   44,   71,   44,   72,   70,
      169,   71,   49,   72,  168,   73,   74,   49,   75,   66,
       73,   74,   76,   75,   78,   77,   81,   76,   80,   78,
       77,   81,   82,   80,   69,   79,   67,   82,   68,   83,
       79,   73,   70,   84,   83,   99,  167,   99,   84,   85,
       78,   71,   72,  104,   85,  104,  139,   86,   74,   87,
       81,   75,   86,   78,   87,  138,  137,   76,   77,   80,
       79,   82,   88,   89,  136,   90,   91,   88,   89,   84,
       90,   83,   92,  140,  135,  140,   93,   92,   85,   91,
       91,   93,  134,  103,   94,   91,   95,   87,   86,   94,

       97,   95,   97,  171,   97,  171,   98,   90,   98,  105,
       98,  102,  106,  107,  105,  108,   89,  106,  107,  109,
      108,  211,  101,  211,  109,   92,  110,   93,   91,  111,
       95,  110,  112,   91,  111,  100,   61,  112,   94,  113,
      106,  107,   60,  249,  113,  249,   59,  105,  109,  114,
      115,  108,  117,  116,  114,  115,  110,  117,  116,  118,
      119,  112,  120,  121,  118,  119,   57,  120,  121,  113,
      116,  111,  122,  123,  124,  114,  125,  122,  123,  124,
      115,  125,  126,  127,  128,   47,  129,  126,  127,  128,
      119,  129,  130,  117,   24,   23,  131,  130,   22,  118,

      120,  131,  125,  123,  132,  133,  121,  141,  122,  132,
      133,  127,  141,  142,  143,  144,  124,  145,  142,  143,
      144,  147,  145,  146,   18,   11,  147,  149,  146,  146,
      131,    7,  149,  146,  132,  146,  130,  141,    3,  146,
      150,  133,  152,  142,  153,  150,    0,  152,    0,  153,
      148,  147,    0,  143,  144,  148,  148,  148,  151,  154,
      148,  148,  148,  151,  154,  155,    0,  148,  148,    0,
      155,  151,  154,    0,  156,    0,  157,  154,  154,  156,
      155,  157,  152,  150,  158,  159,  160,  153,  156,  158,
      159,  160,  161,  162,  164,  165,  163,  161,  162,  164,

      165,  163,  172,  166,  173,  174,  175,  172,  166,  173,
      174,  175,  176,    0,  158,  177,  160,  176,  178,  179,
      177,  180,  183,  178,  179,    0,  180,  183,    0,    0,
      172,  181,  164,  166,  181,  161,  162,  163,  176,  181,
      180,  182,  173,  174,  184,  185,  182,    0,  178,  184,
      185,  186,  175,  179,  177,  187,  186,    0,  188,  189,
      187,    0,  181,  188,  189,    0,  183,  182,  190,  191,
      181,  193,  194,  190,  191,  192,  193,  194,    0,  195,
      192,  196,    0,  185,  195,  184,  196,  197,  188,  189,
      186,  198,  197,  192,  192,  187,  198,  199,  190,  191,

      200,    0,  199,  201,  202,  200,  194,  212,  201,  202,
      193,  213,  212,  195,  214,  196,  213,  198,  197,  214,
        0,  215,    0,    0,  217,  197,  215,  216,  215,  217,
        0,  199,  216,    0,  219,  201,  218,  220,  200,  219,
      221,  218,  220,  222,  223,  221,    0,    0,  222,  223,
      212,  224,  214,  226,  213,  216,  224,  225,  226,  228,
        0,    0,  225,    0,  228,  217,  219,  218,  221,  227,
      229,  220,  230,  231,  227,  229,    0,  230,  231,    0,
      232,  226,    0,    0,  230,  232,  222,  223,  230,  228,
      233,    0,  224,  234,  235,  233,  225,  227,  234,  235,

      237,  236,  231,  238,  239,  237,  236,  229,  238,  239,
      232,  240,  241,    0,  242,  243,  240,  241,  240,  242,
      243,  250,    0,  251,  233,  252,  250,  234,  251,  237,
      252,  238,    0,    0,  253,  239,  254,  235,  236,  253,
      255,  254,  256,  257,  258,  255,    0,  256,  257,  258,
      241,  259,  261,  242,  260,  252,  259,  261,  262,  260,
      263,  265,  264,  262,  266,  263,  265,  264,    0,  266,
      267,  254,  268,  258,  269,  267,  257,  268,  253,  269,
        0,  259,    0,    0,  270,  256,  255,  265,  260,  270,
        0,  271,    0,    0,  266,  261,  271,  263,  264,  272,

      273,  274,  268,  262,  272,  273,  274,  275,  269,  276,
      267,  277,  275,    0,  276,    0,  277,  278,  270,    0,
      271,  279,  278,  280,  278,  282,  279,  283,  280,  273,
      282,    0,  283,  284,    0,    0,  272,  275,  284,  276,
      274,  285,    0,  286,  287,  288,  285,  279,  286,  287,
      288,  290,  289,  282,  277,  291,  290,  289,  293,  292,
      291,  280,    0,  293,  292,  294,  295,  285,  283,  296,
      294,  295,  297,  298,  296,  288,  293,  297,  298,  299,
        0,  300,    0,    0,  299,  291,  300,  287,  289,  292,
      302,  301,  303,    0,  290,  302,  301,  303,  296,  294,

      304,  305,  297,  307,  298,  304,  305,  300,  307,  295,
      306,  299,  301,  301,  301,  306,  309,    0,  308,  310,
      302,  309,  303,  308,  310,  311,  312,  314,  313,    0,
      311,  312,  314,  313,  315,  316,    0,    0,  317,  315,
      316,  304,  305,  317,  308,  318,  319,  307,    0,  306,
      318,  319,  321,  309,  320,  322,  323,  321,  324,  320,
      322,  323,  325,  324,    0,  316,    0,  325,  311,  313,
      326,  312,    0,  315,    0,  326,  327,  323,  323,  323,
      328,  327,  317,    0,    0,  328,  318,  329,  320,  322,
      321,  330,  329,  331,    0,  333,  330,  332,  331,  324,

      333,  334,  332,  326,  335,  325,  334,  336,  337,  335,
      338,  339,  336,  337,  340,  338,  339,  341,  342,  340,
      343,  344,  341,  342,  345,  343,  344,  346,  347,  345,
      348,    0,  346,  347,  331,  348,  332,  349,  350,    0,
      338,    0,  349,  350,  340,  337,  341,  351,  336,  352,
      344,  353,  351,    0,  352,  354,  353,  355,  347,    0,
      354,  343,  355,  356,  346,  357,    0,  358,  356,  348,
      357,  345,  358,  359,  360,  352,  361,  362,  359,  360,
      363,  361,  362,  364,  366,  363,  365,  367,  364,  366,
        0,  365,  367,    0,  368,  357,  369,  358,  354,  368,

      370,  369,  371,  362,  372,  370,  373,  371,  374,  372,
      363,  373,  375,  374,  359,  376,  365,  375,  377,  378,
      376,  379,  380,  377,  378,  367,  379,  380,  381,  382,
      372,  383,    0,  381,  382,  384,  383,  368,    0,  385,
      384,  386,  387,  371,  385,  378,  386,  387,    0,  373,
      388,    0,    0,  375,    0,  388,  380,    0,    0,    0,
        0,    0,  377,    0,    0,    0,    0,    0,    0,  385,
      382,    0,    0,    0,  384,    0,    0,    0,    0,  386,
      390,    0,  390,  391,    0,  391,  393,    0,  393,  394,
        0,  394,  395,    0,  395,  396,    0,  396,  397,    0,

      397,  398,    0,  398,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389,  389,  389,  389,  389,  389,  389,
      389,  389,  389,  389
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 853 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 2 "lex.l"

#line 1072 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 390 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1205 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 3 "lex.l"
printf("SEMICOLON ");
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 4 "lex.l"
printf("COLON ");
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 5 "lex.l"
printf("PLUS ");
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 6 "lex.l"
printf("MINUS ");
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 7 "lex.l"
printf("MULT");
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 8 "lex.l"
printf("DIV");
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 9 "lex.l"
printf("LP ");
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 10 "lex.l"
printf("RP ");
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 11 "lex.l"
printf("LCB ");
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 12 "lex.l"
printf("RCB ");
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 13 "lex.l"
printf("AND ");
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 14 "lex.l"
printf("LOR ");
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 15 "lex.l"
printf("EQ ");
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 16 "lex.l"
printf("LEQ ");
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 17 "lex.l"
printf("LNEQ ");
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 18 "lex.l"
printf("LT ");
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 19 "lex.l"
printf("LTE ");
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 20 "lex.l"
printf("GT ");
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 21 "lex.l"
printf("GTE ");
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 22 "lex.l"
printf("POW ");
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 23 "lex.l"
printf("LNOT ");
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 24 "lex.l"
printf("PRINT ");
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 25 "lex.l"
printf("ELSE ");
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 26 "lex.l"
printf("IF ");
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 27 "lex.l"
printf("WHILE ");
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 28 "lex.l"
printf("FOR ");
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 29 "lex.l"
printf("TYPE ");
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 30 "lex.l"
printf("RETURN ");
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 31 "lex.l"
printf("CONNECT ");
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 32 "lex.l"
printf("DISCONNECT ");
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 33 "lex.l"
printf("FUNCTION ");
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 34 "lex.l"
printf("READALTITUDE ");
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 35 "lex.l"
printf("READTEMPERATURE ");
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 36 "lex.l"
printf("TURNONCAMERA ");
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 37 "lex.l"
printf("TURNOFFCAMERA ");
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 38 "lex.l"
printf("STARTVIDEO ");
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 39 "lex.l"
printf("PAUSEVIDEO ");
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 40 "lex.l"
printf("STOPVIDEO ");
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 41 "lex.l"
printf("TAKEPICTURE ");
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 42 "lex.l"
printf("SAVEMEDIA ");
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 43 "lex.l"
printf("STARTTIMER ");
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 44 "lex.l"
printf("STOPTIMER ");
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 45 "lex.l"
printf("READFROMTIMER ");
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 46 "lex.l"
printf("READACCELERATION ");
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 47 "lex.l"
printf("READSPEEDX ");
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 48 "lex.l"
printf("READSPEEDY ");
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 49 "lex.l"
printf("READSPEEDZ ");
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 50 "lex.l"
printf("SETSPEEDX ");
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 51 "lex.l"
printf("SETSPEEDY ");
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 52 "lex.l"
printf("SETSPEEDZ ");
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 53 "lex.l"
printf("SETSPEED ");
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 54 "lex.l"
printf("FOLLOWCURVE ");
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 55 "lex.l"
printf("READCURVE ");
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 56 "lex.l"
printf("RISE ");
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 57 "lex.l"
printf("DESCENT ");
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 58 "lex.l"
printf("LAND ");
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 59 "lex.l"
printf("MOVEFORWARD ");
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 60 "lex.l"
printf("MOVEBACK ");
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 61 "lex.l"
printf("MOVERIGHT ");
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 62 "lex.l"
printf("MOVELEFT ");
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 63 "lex.l"
printf("ROTATELEFT ");
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 64 "lex.l"
printf("ROTATERIGHT ");
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 65 "lex.l"
printf("WAIT ");
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 66 "lex.l"
printf("READBATTERY ");
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 67 "lex.l"
printf("READLOCATION ");
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 68 "lex.l"
printf("READINCLINE ");
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 69 "lex.l"
printf("STOPMOTOR ");
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 70 "lex.l"
printf("BOOLEAN_LITERAL ");
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 71 "lex.l"
printf("COMMENT ");
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 72 "lex.l"
printf("IDENTIFIER ");
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 73 "lex.l"
printf("IP_ADDRESS ");
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 74 "lex.l"
printf("INTEGER_LITERAL ");
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 75 "lex.l"
printf("FLOAT_LITERAL ");
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 76 "lex.l"
printf("STRING_LITERAL ");
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 77 "lex.l"
;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 78 "lex.l"
;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 79 "lex.l"
ECHO;
	YY_BREAK
#line 1514 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 390 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 390 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 389);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

int main (void);

int main ()
{

	yylex();

	return 0;
}

#line 79 "lex.l"
